### ISSUE TITLE
Error on document replication

### ISSUE THREAD

**Issue by simone-marcon** [bitnami/bitnami-docker-couchdb#3]
I have 3 CouchDb node in Azure, each one in a container instance (Linux machine).
When creating a replication doc, it crashes after a few minute reporting info changes_reader_died.

The replication is created via curl command:

```bash
curl -X POST https://my-couchdb-address/_replicator -H 'Content-Type: application/json' -d '{
"_id": "my-id",
"source": "https://my-couchdb-address/database-name",
"target": "https://my-couchdb-address/database-name",
"create_target": false,
"continuous": true
}'
```

CouchDb installed version is 2.3.1

Log extract of the error reported:

[couch_error.log](https://github.com/bitnami/bitnami-docker-couchdb/files/5207219/couch_error.log)
[couch_debug.log](https://github.com/bitnami/bitnami-docker-couchdb/files/5207220/couch_debug.log)

**Comment by juan131** [comment]
Hi @simone-marcon 

Could you please share how you configured your CouchDB containers? I mean, the environment you defined, mounted volumes, etc. I'd like to reproduce a similar environment on my side to see what's going on.

**Comment by simone-marcon** [comment]
Hi @juan131 ,

the containers were created not by me, directly on azure portal. I exported the template directly from azure, is this enough?

[ExportedTemplate-zulu-e.zip](https://github.com/bitnami/bitnami-docker-couchdb/files/5217640/ExportedTemplate-zulu-e.zip)

**Comment by juan131** [comment]
Hi @simone-marcon 

Taking a look to the `template.json` file you shared, I noticed you defined the environments below on your CouchDB container(s):

```json
"environmentVariables": [
    {
        "name": "COUCHDB_USER",
        "value": "user"
    },
    {
        "name": "COUCHDB_PASSWORD",
        "value": "password"
    },
    {
        "name": "NODENAME",
        "value": "[concat(parameters('containerGroups_zulue_couchdb01_name'), '.westeurope.azurecontainer.io')]"
    },
    {
        "name": "ERL_FLAGS",
        "value": "-setcookie \"gTmusoYeRN_9aN-LVK7yF8cjKuGEx0ZQ\" -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9100"
    }
],
```

Please note that, when creating a CouchDB cluster with N nodes, you have to define the environment variables `COUCHDB_NODENAME`, `COUCHDB_CLUSTER_PORT_NUMBER`, and `COUCHDB_CREATE_DATABASES` as it's detailed in the link below:

- https://github.com/bitnami/bitnami-docker-couchdb#clustering-configuration

**Comment by simone-marcon** [comment]
Hi @juan131, sorry but I'm a litttle busy on these days. Have you had time to reproduce my environment? Does it gives you the same error? If yes, adding the environment variables you suggested me does makes the system works well?

I'm not trying to make you do my job, I'm only asking if you had the time to try it and have some result. I'll try your suggestion as soon as I'll have some free time.

**Comment by juan131** [comment]
Hi @simone-marcon 

Yes, I tried to reproduce it using the Docker Compose below:

```yaml
version: '2'
services:
  couchdb-0:
    image: docker.io/bitnami/couchdb:3-debian-10
    environment:
      - BITNAMI_DEBUG=true
      - COUCHDB_USER=someuser
      - COUCHDB_PASSWORD=somepass
      - COUCHDB_NODENAME=couchdb-0@couchdb-0
      - COUCHDB_CREATE_DATABASES=yes
      - COUCHDB_PORT_NUMBER=5984
      - COUCHDB_CLUSTER_PORT_NUMBER=9100
    volumes:
      - couchdb_0_data:/bitnami/couchdb
  couchdb-1:
    image: docker.io/bitnami/couchdb:3-debian-10
    environment:
      - BITNAMI_DEBUG=true
      - COUCHDB_USER=someuser
      - COUCHDB_PASSWORD=somepass
      - COUCHDB_NODENAME=couchdb-1@couchdb-1
      - COUCHDB_CREATE_DATABASES=no
      - COUCHDB_PORT_NUMBER=5984
      - COUCHDB_CLUSTER_PORT_NUMBER=9100
    volumes:
      - couchdb_1_data:/bitnami/couchdb
  couchdb-2:
    image: docker.io/bitnami/couchdb:3-debian-10
    environment:
      - BITNAMI_DEBUG=true
      - COUCHDB_USER=someuser
      - COUCHDB_PASSWORD=somepass
      - COUCHDB_NODENAME=couchdb-2@couchdb-2
      - COUCHDB_CREATE_DATABASES=no
      - COUCHDB_PORT_NUMBER=5984
      - COUCHDB_CLUSTER_PORT_NUMBER=9100
    volumes:
      - couchdb_2_data:/bitnami/couchdb

volumes:
  couchdb_0_data:
    driver: local
  couchdb_1_data:
    driver: local
  couchdb_2_data:
    driver: local
```

Then, I run the commands below to test it:

```console
$ docker-compose up -d
$ docker-compose exec couchdb-0 bash
$ curl -X POST http://someuser:somepass@couchdb-0:5984/_replicator -H 'Content-Type: application/json' -d '{
"_id": "my-id",
"source": "http://couchdb-0:5984/database-name",
"target": "http://couchdb-0:5984/database-name",
"create_target": false,
"continuous": true
}'
{"ok":true,"id":"my-id","rev":"1-c4685d01793954d42df3eef0309ce9d5"}
```
