### ISSUE TITLE
Container start not possible: timeout reached before the port went into state "inuse"

### ISSUE THREAD

**Issue by mialeto** [bitnami/bitnami-docker-couchdb#5]
### Name and Version

bitnami/couchdb:3

### What steps will reproduce the bug?

My environment is as follows:
- Debian 4.19.208-1 x86_64
- Docker version 20.10.12, build e91ed57
- docker-compose version 1.26.2, build eefe0d31
- docker-info:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 41
  Running: 40
  Paused: 0
  Stopped: 1
 Images: 65
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-18-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.6GiB
 Name: *********
 ID: ***********************************************************************
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Container was started via docker-compose up -d

Docker-compose.yml configuration part looks like this:

```
  couchdb:
    image: docker.io/bitnami/couchdb:3
#   user: root
    container_name: net_couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=/run/secrets/db_admin_secret
      - COUCHDB_NODENAME=steves_couch@127.0.0.1
      - COUCHDB_PORT_NUMBER=5984
      - COUCHDB_BIND_ADDRESS=0.0.0.0
    secrets:
      - source: db_admin_secret
#   ports:
#     - '5984:5984'
#     - '4369:4369'
#     - '9100:9100'
    restart: unless-stopped
    networks:
      - net_standard
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/services/database/volumes/couchdb_data:/bitnami/couchdb
      - /var/services/database/volumes/couchdb_config:/opt/bitnami/couchdb/etc
```

### What is the expected behavior?

Expected behaviour is container starts and does not fail

### What do you see instead?

```
couchdb 16:49:52.41 Welcome to the Bitnami couchdb container
couchdb 16:49:52.42 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-couchdb
couchdb 16:49:52.42 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-couchdb/issues
couchdb 16:49:52.42
couchdb 16:49:52.42 INFO  ==> ** Starting CouchDB setup **
couchdb 16:49:52.55 INFO  ==> Initializing CouchDB...
couchdb 16:49:52.55 INFO  ==> Updating '/opt/bitnami/couchdb/etc/default.d/10-bitnami.ini' based on user configuration...
couchdb 16:49:53.32 INFO  ==> Updating '/opt/bitnami/couchdb/etc/vm.args' based on user configuration...
couchdb 16:49:53.38 INFO  ==> Deploying CouchDB from scratch
couchdb 16:49:53.38 INFO  ==> Starting CouchDB in background...
timeout reached before the port went into state "inuse"

```

### Additional information

I found references saying this can result from missing configuration variables, which is why I set some even though they remain on their default values. Didn't do anything...
